create table books (
	id INT AUTO_INCREMENT,
	isbn VARCHAR(50),
	title VARCHAR(50),
	author VARCHAR(50),
	publisher VARCHAR(50),
	pages INT,
    PRIMARY KEY (id)
);
insert into books (id, isbn, title, author, publisher, pages) values (1, '516066267-7', 'Malice', 'Evvie Shilliday', 'Amazon parrot (unidentified)', 56);
insert into books (id, isbn, title, author, publisher, pages) values (2, '457258580-6', 'Stalingrad', 'Harlene Aykroyd', 'Penguin, magellanic', 476);
insert into books (id, isbn, title, author, publisher, pages) values (3, '034522347-0', 'Lassie', 'Frederique Belham', 'Owl, white-browed', 260);
insert into books (id, isbn, title, author, publisher, pages) values (4, '328000761-5', 'Newton Boys, The', 'Helga Roskilly', 'Coatimundi, ring-tailed', 375);
insert into books (id, isbn, title, author, publisher, pages) values (5, '718781451-8', 'DNA', 'Melodee Allington', 'Aardwolf', 68);
insert into books (id, isbn, title, author, publisher, pages) values (6, '995838036-6', 'Angels with Dirty Faces', 'Rhett Burdus', 'Lilac-breasted roller', 201);
insert into books (id, isbn, title, author, publisher, pages) values (7, '621577409-X', 'After the Rehearsal (Efter repetitionen)', 'Daryle Maplesden', 'Capuchin, black-capped', 274);
insert into books (id, isbn, title, author, publisher, pages) values (8, '683978763-X', 'Cherish', 'Jennilee Franiak', 'Zebra, common', 468);
insert into books (id, isbn, title, author, publisher, pages) values (9, '787668123-9', 'It Conquered the World', 'Carmelle Perceval', 'Suricate', 221);
insert into books (id, isbn, title, author, publisher, pages) values (10, '775396658-8', 'Shadows in an Empty Room', 'Elvina Stradling', 'Common duiker', 76);
insert into books (id, isbn, title, author, publisher, pages) values (11, '434002159-8', 'Gainsbourg (Vie Héroïque)', 'Selia Peoples', 'Pie, indian tree', 47);
insert into books (id, isbn, title, author, publisher, pages) values (12, '745863218-6', 'Train on the Brain', 'Abrahan Noddles', 'Emerald green tree boa', 395);
insert into books (id, isbn, title, author, publisher, pages) values (13, '460102209-6', 'Big Wedding, The', 'Zorah Succamore', 'Deer, white-tailed', 205);
insert into books (id, isbn, title, author, publisher, pages) values (14, '908763046-8', 'The Things of Life', 'Emmye Simoncello', 'Fox, asian red', 471);
insert into books (id, isbn, title, author, publisher, pages) values (15, '719251066-1', 'Trigun: Badlands Rumble', 'Adrianna Kumaar', 'Armadillo, seven-banded', 257);
insert into books (id, isbn, title, author, publisher, pages) values (16, '284322192-7', 'Dark Angel (I Come in Peace)', 'Thomasin Szapiro', 'White rhinoceros', 188);
insert into books (id, isbn, title, author, publisher, pages) values (17, '242723971-2', 'Short Circuit', 'Borden Arkell', 'Turkey vulture', 308);
insert into books (id, isbn, title, author, publisher, pages) values (18, '602354550-5', 'Baron of Arizona, The', 'Evelin MacCourt', 'Ox, musk', 443);
insert into books (id, isbn, title, author, publisher, pages) values (19, '693096962-1', 'Third Person', 'Shauna Bruckman', 'Monitor, water', 250);
insert into books (id, isbn, title, author, publisher, pages) values (20, '310619121-X', 'Patch of Blue, A', 'Marie-jeanne Linwood', 'European beaver', 362);
insert into books (id, isbn, title, author, publisher, pages) values (21, '168805273-9', 'Cheri', 'Erminia MacInnes', 'Fox, blue', 425);
insert into books (id, isbn, title, author, publisher, pages) values (22, '809969823-1', 'Testament of Orpheus, The (Testament d''Orphée)', 'Kamila Rose', 'Sockeye salmon', 222);
insert into books (id, isbn, title, author, publisher, pages) values (23, '922999599-1', 'Mystery of the 13th Guest', 'Sharron Corthes', 'Squirrel, eurasian red', 137);
insert into books (id, isbn, title, author, publisher, pages) values (24, '732277819-7', 'Stephen Tobolowsky''s Birthday Party', 'Tobin Blaine', 'Common pheasant', 353);
insert into books (id, isbn, title, author, publisher, pages) values (25, '043698224-2', 'Nazi Officer''s Wife, The', 'Archie Totterdill', 'Bat, madagascar fruit', 398);
insert into books (id, isbn, title, author, publisher, pages) values (26, '284435287-1', 'Guitar, The', 'Barbaraanne Blakeley', 'Least chipmunk', 498);
insert into books (id, isbn, title, author, publisher, pages) values (27, '574061533-X', 'Undercover Blues', 'Ginnie Attard', 'Gonolek, burchell''s', 52);
insert into books (id, isbn, title, author, publisher, pages) values (28, '347046126-0', 'Lebanon, Pa.', 'Beulah Rodder', 'Snake-necked turtle', 149);
insert into books (id, isbn, title, author, publisher, pages) values (29, '239789945-0', 'Hey, Happy!', 'Ham Squire', 'Dik, kirk''s dik', 81);
insert into books (id, isbn, title, author, publisher, pages) values (30, '928931690-X', 'Caine (Shark!)', 'Kirbee Cornelius', 'Boa, emerald green tree', 263);
insert into books (id, isbn, title, author, publisher, pages) values (31, '905720083-X', 'Cleopatra', 'Leupold Reiglar', 'Kingfisher, malachite', 189);
insert into books (id, isbn, title, author, publisher, pages) values (32, '903971662-5', 'Fly II, The', 'Lauri Oswal', 'Swan, black', 257);
insert into books (id, isbn, title, author, publisher, pages) values (33, '402978685-5', 'Lady Chatterley''s Lover', 'Brnaba Kits', 'Lava gull', 17);
insert into books (id, isbn, title, author, publisher, pages) values (34, '422009296-X', 'Tarzan Finds a Son!', 'Annadiane Probbing', 'Amazon parrot (unidentified)', 160);
insert into books (id, isbn, title, author, publisher, pages) values (35, '234385864-0', 'Touch of Sin, A (Tian zhu ding)', 'Ron Goforth', 'Spotted-tailed quoll', 234);
insert into books (id, isbn, title, author, publisher, pages) values (36, '534625684-9', 'Expert, The', 'Coralie Sheridan', 'Bee-eater, white-fronted', 177);
insert into books (id, isbn, title, author, publisher, pages) values (37, '408926107-4', 'Perfect Crime, The (Crimen Ferpecto) (Ferpect Crime)', 'Sandi Shury', 'Japanese macaque', 130);
insert into books (id, isbn, title, author, publisher, pages) values (38, '941526821-2', 'Filthy Gorgeous: The Bob Guccione Story', 'Pansie Cowern', 'Malleefowl', 243);
insert into books (id, isbn, title, author, publisher, pages) values (39, '958816102-9', 'Humboldt County', 'Alejandrina Scarman', 'Netted rock dragon', 28);
insert into books (id, isbn, title, author, publisher, pages) values (40, '475661777-8', 'Who Killed Bambi? (Qui a tué Bambi?)', 'Darb Blakiston', 'Killer whale', 85);
insert into books (id, isbn, title, author, publisher, pages) values (41, '104001258-2', 'Fuck You, Goethe (Fack Ju Göhte)', 'Marthena Birchwood', 'Tern, arctic', 179);
insert into books (id, isbn, title, author, publisher, pages) values (42, '938102094-9', 'Gumby: The Movie', 'Ervin Sarvar', 'Puku', 170);
insert into books (id, isbn, title, author, publisher, pages) values (43, '932281473-X', 'I Remember (Eu Me Lembro)', 'Austin Hay', 'Sun gazer', 147);
insert into books (id, isbn, title, author, publisher, pages) values (44, '867692267-5', 'Waltz with Bashir (Vals im Bashir)', 'Hobard Warsap', 'Roadrunner, greater', 110);
insert into books (id, isbn, title, author, publisher, pages) values (45, '172456922-8', 'Dog Day Afternoon', 'Inness Alabaster', 'Squirrel, grey-footed', 163);
insert into books (id, isbn, title, author, publisher, pages) values (46, '682763910-X', 'Death at a Funeral', 'Benjy Bilton', 'Glider, feathertail', 419);
insert into books (id, isbn, title, author, publisher, pages) values (47, '431147290-0', 'Black Narcissus', 'Caryl Huriche', 'Cape fox', 455);
insert into books (id, isbn, title, author, publisher, pages) values (48, '488058574-2', 'Warrior of the Lost World', 'Birgit Weatherup', 'Dove, galapagos', 300);
insert into books (id, isbn, title, author, publisher, pages) values (49, '150561218-7', 'California', 'Sargent Despenser', 'Eland, common', 340);
insert into books (id, isbn, title, author, publisher, pages) values (50, '671920432-7', 'White Rose, The (Weiße Rose, Die)', 'Keri Osan', 'Snowy egret', 269);
insert into books (id, isbn, title, author, publisher, pages) values (51, '795412857-1', 'Buckskin Frontier', 'Bobbie Esmead', 'Northern elephant seal', 270);
insert into books (id, isbn, title, author, publisher, pages) values (52, '491156712-0', 'Yentl', 'Elinor Hutsby', 'Sungazer, yellow-brown', 66);
insert into books (id, isbn, title, author, publisher, pages) values (53, '392524769-6', 'Erased (Expatriate, The)', 'Evelina Laurenzi', 'Grouse, greater sage', 227);
insert into books (id, isbn, title, author, publisher, pages) values (54, '537188510-2', 'S.O.B.', 'Nelie Detloff', 'Lesser double-collared sunbird', 219);
insert into books (id, isbn, title, author, publisher, pages) values (55, '431399342-8', 'Bitter Tea of General Yen, The', 'Bord Stirtle', 'Dabchick', 321);
insert into books (id, isbn, title, author, publisher, pages) values (56, '261480168-2', 'Crime of Father Amaro, The (Crimen del padre Amaro, El)', 'Laetitia Thorneywork', 'Goose, andean', 231);
insert into books (id, isbn, title, author, publisher, pages) values (57, '380969002-3', 'Happenstance (Battement d''ailes du papillon, Le)', 'Gunar Butt Gow', 'Hen, sage', 79);
insert into books (id, isbn, title, author, publisher, pages) values (58, '826977093-0', 'American Scary', 'Ardith Kyte', 'Squirrel, smith''s bush', 351);
insert into books (id, isbn, title, author, publisher, pages) values (59, '063953385-X', 'Beautiful Girl', 'Lindsy Andrea', 'Uinta ground squirrel', 47);
insert into books (id, isbn, title, author, publisher, pages) values (60, '185301000-6', 'Come Early Morning', 'Emelita Small', 'Boa, malagasy ground', 292);
insert into books (id, isbn, title, author, publisher, pages) values (61, '566771253-9', 'War Stories', 'Ediva Choppin', 'Japanese macaque', 18);
insert into books (id, isbn, title, author, publisher, pages) values (62, '701913915-9', 'Fight, Zatoichi, Fight (Zatôichi kesshô-tabi) (Zatôichi 8)', 'Gladi Engledow', 'Eastern white pelican', 335);
insert into books (id, isbn, title, author, publisher, pages) values (63, '514528946-4', 'House Arrest', 'Junina Raphael', 'Egyptian viper', 199);
insert into books (id, isbn, title, author, publisher, pages) values (64, '586749253-2', 'Narrow Margin, The', 'Siffre Silveston', 'Aardwolf', 279);
insert into books (id, isbn, title, author, publisher, pages) values (65, '818852985-0', 'Fern flowers (Fleur de fougère)', 'Avie Hinrichs', 'Black-collared barbet', 90);
insert into books (id, isbn, title, author, publisher, pages) values (66, '438739465-X', 'Beauty in Trouble (Kráska v nesnázích)', 'Judas Fawdrey', 'Yellow-billed stork', 398);
insert into books (id, isbn, title, author, publisher, pages) values (67, '345293551-5', 'In Old Arizona', 'Renard Harner', 'Striped skunk', 411);
insert into books (id, isbn, title, author, publisher, pages) values (68, '876309307-3', 'Eaux d''artifice', 'Erik Carnow', 'Vine snake (unidentified)', 414);
insert into books (id, isbn, title, author, publisher, pages) values (69, '175961519-6', 'Derailed', 'Lazarus Barnett', 'House crow', 398);
insert into books (id, isbn, title, author, publisher, pages) values (70, '522697256-3', 'Saints and Soldiers: Airborne Creed', 'Jacky Gladdor', 'Black-cheeked waxbill', 348);
insert into books (id, isbn, title, author, publisher, pages) values (71, '102202765-4', 'Kids Are All Right, The', 'Edythe Checklin', 'Scottish highland cow', 241);
insert into books (id, isbn, title, author, publisher, pages) values (72, '499183177-6', 'Moon Is Blue, The', 'Dotti Gandley', 'Hyena, brown', 397);
insert into books (id, isbn, title, author, publisher, pages) values (73, '026684492-8', 'Divine Horsemen: The Living Gods of Haiti', 'Sandro Wardingly', 'American alligator', 385);
insert into books (id, isbn, title, author, publisher, pages) values (74, '635542553-5', 'Saratov Approach, The', 'Rolph Ioan', 'Plover, three-banded', 427);
insert into books (id, isbn, title, author, publisher, pages) values (75, '863649991-7', 'Asier ETA biok', 'Sacha Tomaskunas', 'Spoonbill, white', 249);
insert into books (id, isbn, title, author, publisher, pages) values (76, '160558320-0', 'Tatsumi', 'Jewelle Lang', 'Dog, black-tailed prairie', 344);
insert into books (id, isbn, title, author, publisher, pages) values (77, '942381905-2', 'Oranges', 'Kellen Jales', 'Cat, cape wild', 360);
insert into books (id, isbn, title, author, publisher, pages) values (78, '989287096-4', 'FLCL', 'Stacey Aust', 'Squirrel, malabar', 103);
insert into books (id, isbn, title, author, publisher, pages) values (79, '371897662-5', 'Always Leave Them Laughing', 'Alysa Kidde', 'Macaque, japanese', 250);
insert into books (id, isbn, title, author, publisher, pages) values (80, '505749553-4', 'It''s in the Water', 'Granny Garwill', 'Nyala', 311);
insert into books (id, isbn, title, author, publisher, pages) values (81, '629910311-6', 'Spice World', 'Gwenny Guitel', 'Cereopsis goose', 496);
insert into books (id, isbn, title, author, publisher, pages) values (82, '480588898-9', 'Heart Like a Wheel', 'Eliza de Bullion', 'Salmon, sockeye', 366);
insert into books (id, isbn, title, author, publisher, pages) values (83, '475604705-X', 'Place in the Sun, A (En plats i solen)', 'Madelene Lace', 'Pie, indian tree', 432);
insert into books (id, isbn, title, author, publisher, pages) values (84, '231140259-5', 'Lola', 'Justen Davy', 'Fox, north american red', 111);
insert into books (id, isbn, title, author, publisher, pages) values (85, '277174417-1', 'Lodger: A Story of the London Fog, The', 'Lynn Derham', 'Ring-tailed gecko', 91);
insert into books (id, isbn, title, author, publisher, pages) values (86, '645231637-0', 'Ilsa, She Wolf of the SS', 'Merridie Brownscombe', 'Little brown dove', 251);
insert into books (id, isbn, title, author, publisher, pages) values (87, '289090170-X', 'Land Without Bread (Hurdes, tierra sin pan, Las)', 'Alisander Morbey', 'Vulture, griffon', 474);
insert into books (id, isbn, title, author, publisher, pages) values (88, '560485860-9', 'Escanaba in da Moonlight', 'Jard Dorber', 'Magpie, australian', 108);
insert into books (id, isbn, title, author, publisher, pages) values (89, '333979241-0', 'Red Tent, The (Krasnaya palatka)', 'Charmane Kondratenya', 'Hornbill, leadbeateri''s ground', 111);
insert into books (id, isbn, title, author, publisher, pages) values (90, '966843422-6', 'Running With Scissors', 'Bibby Dougliss', 'Paca', 441);
insert into books (id, isbn, title, author, publisher, pages) values (91, '866310038-8', 'Life', 'Dillie Willans', 'Striped skunk', 362);
insert into books (id, isbn, title, author, publisher, pages) values (92, '195230117-3', 'Naked Edge, The', 'Glynda Farndale', 'Cheetah', 413);
insert into books (id, isbn, title, author, publisher, pages) values (93, '298409163-9', 'Three Marias, The (Três Marias, As)', 'Dom Hastin', 'Wallaby, whip-tailed', 231);
insert into books (id, isbn, title, author, publisher, pages) values (94, '257622721-X', 'Last Time I Committed Suicide, The', 'Anne-marie Carmichael', 'Nuthatch, red-breasted', 451);
insert into books (id, isbn, title, author, publisher, pages) values (95, '874078357-X', 'Betty Blue (37°2 le matin)', 'Candra Dulinty', 'Small-spotted genet', 46);
insert into books (id, isbn, title, author, publisher, pages) values (96, '713052387-5', 'Steak', 'Salvatore Swigg', 'Bulbul, african red-eyed', 416);
insert into books (id, isbn, title, author, publisher, pages) values (97, '142378773-0', 'No Way Home', 'Joane Greason', 'Sandhill crane', 57);
insert into books (id, isbn, title, author, publisher, pages) values (98, '627592559-0', 'Deadly Surveillance', 'Denys Queree', 'Bee-eater (unidentified)', 254);
insert into books (id, isbn, title, author, publisher, pages) values (99, '556995404-X', 'Last Days Here', 'Seward Gounin', 'Paddy heron (unidentified)', 186);
insert into books (id, isbn, title, author, publisher, pages) values (100, '426228452-2', 'Lady Oscar', 'Cindy Ebbing', 'Dik, kirk''s dik', 56);
insert into books (id, isbn, title, author, publisher, pages) values (101, '461686634-1', 'Judgement in Stone, A (Cérémonie, La)', 'Jacques Audley', 'Stork, marabou', 181);
insert into books (id, isbn, title, author, publisher, pages) values (102, '618044854-X', 'Our Song', 'Sean Wavell', 'Scottish highland cow', 156);
insert into books (id, isbn, title, author, publisher, pages) values (103, '275334513-9', 'Whores'' Glory', 'Martainn Curtoys', 'Common goldeneye', 458);
insert into books (id, isbn, title, author, publisher, pages) values (104, '039669827-1', 'Red Heat', 'Tanner Sedge', 'Malleefowl', 445);
insert into books (id, isbn, title, author, publisher, pages) values (105, '068993761-X', 'Cloudland', 'Walden Djakovic', 'White-necked raven', 110);
insert into books (id, isbn, title, author, publisher, pages) values (106, '827593310-2', 'We Always Lie to Strangers', 'Willi Sturmey', 'Cook''s tree boa', 336);
insert into books (id, isbn, title, author, publisher, pages) values (107, '783219148-1', 'JCVD', 'Krissie Cheke', 'Chacma baboon', 253);
insert into books (id, isbn, title, author, publisher, pages) values (108, '374816558-7', 'Sitting Bull', 'Michel Kitman', 'California sea lion', 57);
insert into books (id, isbn, title, author, publisher, pages) values (109, '973437423-0', 'Mistress America', 'Abbey Ollis', 'Chameleon (unidentified)', 79);
insert into books (id, isbn, title, author, publisher, pages) values (110, '137356345-1', 'Westward Ho', 'Gui Streader', 'Crake, african black', 140);
insert into books (id, isbn, title, author, publisher, pages) values (111, '945422683-5', 'American Reunion (American Pie 4)', 'Tarrance Ovize', 'Stanley crane', 120);
insert into books (id, isbn, title, author, publisher, pages) values (112, '819820534-9', 'Nokas', 'Bree Plan', 'White-faced tree rat', 90);
insert into books (id, isbn, title, author, publisher, pages) values (113, '724301269-8', 'Mao''s Last Dancer', 'Fanchon Cowan', 'Greater adjutant stork', 490);
insert into books (id, isbn, title, author, publisher, pages) values (114, '848129202-8', 'War of the Arrows (Choi-jong-byeong-gi Hwal)', 'Elston Byart', 'Bulbul, african red-eyed', 29);
insert into books (id, isbn, title, author, publisher, pages) values (115, '958892774-9', 'Beauty and the Beast (Belle et la bête, La)', 'Cullen Crunkhorn', 'Raccoon, crab-eating', 405);
insert into books (id, isbn, title, author, publisher, pages) values (116, '394508279-X', 'The Power and the Glory', 'Lulu Calver', 'Caiman, spectacled', 482);
insert into books (id, isbn, title, author, publisher, pages) values (117, '888336525-9', 'Sugar Curtain, The (El telón de azúcar)', 'Renato Bunny', 'Red-knobbed coot', 197);
insert into books (id, isbn, title, author, publisher, pages) values (118, '548205270-2', 'Matter of Taste, A (Affaire de Goût, Une)', 'Hazel Sergent', 'Gnu, brindled', 14);
insert into books (id, isbn, title, author, publisher, pages) values (119, '374393174-5', 'Attack of the Crab Monsters', 'Stevy Izakof', 'Sulfur-crested cockatoo', 25);
insert into books (id, isbn, title, author, publisher, pages) values (120, '201395493-X', 'The Stoker', 'Dominga Brixey', 'White rhinoceros', 64);
insert into books (id, isbn, title, author, publisher, pages) values (121, '650035469-9', 'These Amazing Shadows', 'Armin Danell', 'Mara', 206);
insert into books (id, isbn, title, author, publisher, pages) values (122, '059526204-X', 'Repo! The Genetic Opera', 'Udell Plowes', 'Agama lizard (unidentified)', 406);
insert into books (id, isbn, title, author, publisher, pages) values (123, '546283404-7', 'Razor''s Edge, The', 'Fonsie MacGuigan', 'Marmot, yellow-bellied', 23);
insert into books (id, isbn, title, author, publisher, pages) values (124, '044467823-9', 'Taxi', 'Alistair Andreou', 'Common grenadier', 486);
insert into books (id, isbn, title, author, publisher, pages) values (125, '132270767-7', 'Prince of Egypt, The', 'Hermon Bartolommeo', 'Reindeer', 192);
insert into books (id, isbn, title, author, publisher, pages) values (126, '901290949-X', 'Amazing Panda Adventure, The', 'Elmore McGinnis', 'Heron, grey', 414);
insert into books (id, isbn, title, author, publisher, pages) values (127, '764840693-4', 'Alibi, The (Lies and Alibis)', 'Elden Darree', 'Iguana, land', 295);
insert into books (id, isbn, title, author, publisher, pages) values (128, '703947007-1', 'Blueprint for Murder, A', 'Rainer Windram', 'Plains zebra', 195);
insert into books (id, isbn, title, author, publisher, pages) values (129, '298836595-4', 'Our Little Differences (Die feinen Unterschiede)', 'Abel Foster-Smith', 'Falcon, prairie', 123);
insert into books (id, isbn, title, author, publisher, pages) values (130, '484647806-8', 'Dangerous Corner', 'Kathe Blasiak', 'Wolf spider', 419);
insert into books (id, isbn, title, author, publisher, pages) values (131, '404626134-X', 'Electrick Children', 'Darnell Gossan', 'South American sea lion', 497);
insert into books (id, isbn, title, author, publisher, pages) values (132, '494755572-6', 'Die Fischerin', 'Leilah Moreland', 'Bandicoot, long-nosed', 293);
insert into books (id, isbn, title, author, publisher, pages) values (133, '950625575-X', 'First on the Moon (Pervye na Lune)', 'Hubey Higgonet', 'Field flicker', 15);
insert into books (id, isbn, title, author, publisher, pages) values (134, '210881473-6', 'Enon opetukset', 'Clara Dunniom', 'Bandicoot, long-nosed', 181);
insert into books (id, isbn, title, author, publisher, pages) values (135, '847812990-1', '4th Floor, The', 'Stavro Flagg', 'Crake, african black', 39);
insert into books (id, isbn, title, author, publisher, pages) values (136, '007637766-0', 'Young and the Dead, The', 'Cordelie Jachimczak', 'Roe deer', 156);
insert into books (id, isbn, title, author, publisher, pages) values (137, '245819423-0', 'Charlie and the Chocolate Factory', 'Halli Biasini', 'Armadillo, nine-banded', 483);
insert into books (id, isbn, title, author, publisher, pages) values (138, '940501013-1', 'Fall From Grace', 'Percy Spittles', 'Porcupine, prehensile-tailed', 248);
insert into books (id, isbn, title, author, publisher, pages) values (139, '700684025-2', 'Moscow on the Hudson', 'Chevalier Hutton', 'Stork, jabiru', 169);
insert into books (id, isbn, title, author, publisher, pages) values (140, '673022036-8', 'Valiant', 'Claresta Worthing', 'Common seal', 40);
insert into books (id, isbn, title, author, publisher, pages) values (141, '794454734-2', 'Unholy Three, The', 'Ernie Pavia', 'Cape white-eye', 39);
insert into books (id, isbn, title, author, publisher, pages) values (142, '531276886-3', 'Beneath the 12-Mile Reef', 'Marjy Wilbore', 'Grey phalarope', 95);
insert into books (id, isbn, title, author, publisher, pages) values (143, '521901789-6', 'My Name is Juani (Yo soy la Juani)', 'Emmie Barthrop', 'Weaver, lesser masked', 455);
insert into books (id, isbn, title, author, publisher, pages) values (144, '724820079-4', 'Shampoo', 'Katey Lorenzo', 'Jackal, asiatic', 204);
insert into books (id, isbn, title, author, publisher, pages) values (145, '742444071-3', 'Jesus Camp', 'Viviyan Paur', 'Booby, blue-faced', 395);
insert into books (id, isbn, title, author, publisher, pages) values (146, '647546378-7', 'Boudu Saved From Drowning (Boudu sauvé des eaux)', 'Meridel Peach', 'Egyptian viper', 305);
insert into books (id, isbn, title, author, publisher, pages) values (147, '567684284-9', 'Smokey and the Bandit', 'Henrik Pieter', 'Swallow-tail gull', 249);
insert into books (id, isbn, title, author, publisher, pages) values (148, '739148885-2', 'Blind Spot: Hitler''s Secretary (Im toten Winkel - Hitlers Sekretärin)', 'Anica Ivakhin', 'Goose, knob-nosed', 145);
insert into books (id, isbn, title, author, publisher, pages) values (149, '940984093-7', 'Aftermath: Population Zero', 'Meredeth Jertz', 'Herring gull', 123);
insert into books (id, isbn, title, author, publisher, pages) values (150, '852703294-5', '11 Flowers (Wo 11)', 'Barney Duffett', 'Klipspringer', 449);
